In [23]:
import numpy as np
print(np.zeros([5,3],dtype=np.int32))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Problem 1
Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
Output: [ True False False True False]


In [28]:
import numpy as np
a = np.array([0,10,20,40,60])
b = np.array([0,40])

c = np.in1d(a,b)
print(c)

[ True False False  True False]


Problem 2
Write a NumPy program to get the unique elements of an array
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

In [5]:

import numpy as np
some_input = input("Enter Space seperated inputs").split()
a = []
for i in some_input:
    a.append(int(i))


b = np.array([[1,1],[2,3]])

print(np.unique(a))
print(np.unique(b))

[10 20]
[1 2 3]


Problem 3
Write a NumPy program to sort an along the first, last axis of an array.
Sample array: [[2,5],[4,4]]
Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]

In [6]:
import numpy as np
arr = []
row = int(input("Enter how many rows "))

for i in range(row):
    
    some_input = input("Enter Space seperated inputs").split()
    a = []
    for i in some_input:
        a.append(int(i))

    arr.append(a)


ans = np.sort(arr,axis=-1)
print(ans)
np


[[1 2 5]
 [4 5 6]]



Problem 4
Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
Sample Output:
Original array:
[10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
[4,1,7,3]

In [12]:
import numpy as np
some_input = input("Enter Space seperated inputs").split()
a = []
for i in some_input:
    a.append(int(i))

print(np.unique(a,return_counts=True)[1])




[4 1 7 3]


Problem 5
Write a NumPy program to remove nan values from a given array.
Sample Output:
Original array:
[200. 300. nan nan nan 700.]
After removing nan values:
[200. 300. 700.]

In [15]:
import numpy as np
arr = np.array([200,300,np.nan,np.nan,np.nan,700])

arr = arr[np.logical_not(np.isnan(arr))]

print(arr)

[200. 300. 700.]


Problem 6
Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
Sample Output:
50th percentile (median):
3.0
40th percentile:
2.6
90th percentile:
4.6

In [18]:
import numpy as np
arr = np.array([10,20,50,30,140,20,10,50,30,20,62,25,11])

print("50th percentile (median):")
print(np.percentile(arr,50))

print("40th percentile:")
print(np.percentile(arr,40))

print("90th percentile:")
print(np.percentile(arr,90))

50th percentile (median):
25.0
40th percentile:
20.0
90th percentile:
59.60000000000001


Problem 7
Write a NumPy program to find indices of elements equal to zero in a NumPy array.
Sample Output:
Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal +to zero of the said array:
[1 3 5]

In [26]:
import numpy as np
some_input = input("Enter Space seperated inputs").split()
a = []
for i in some_input:
    a.append(int(i))

a = np.array(a)
print(np.where(a==0)[0])


[ 5 10 11 14]


Problem 8
Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.
Sample Output:
Original array:
[-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]

In [32]:
import numpy as np
some_input = input("Enter Space seperated inputs").split()
a = []
for i in some_input:
    a.append(float(i))

a = np.array(a)
print(np.absolute(np.round(a)))




[2. 2. 6. 8. 9.]


Problem 9
Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
Sample output:
Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[ 0 0 2 2 2 -7 200]

In [35]:
x = np.array([1,3,5,7,0])
x= np.diff(x)
print(x)

new_arr = np.append(x,200)
new_arr = np.insert(new_arr,0,[0,0])
print(new_arr)

[ 2  2  2 -7]
[  0   0   2   2   2  -7 200]


Problem 10
Write a NumPy program to get the indices of the sorted elements of a given array.
Expected Output:
Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]

In [36]:
x = np.array([1023,5202,6230,1671,1682,5241,4532])
print(np.argsort(x))

[0 3 4 6 1 5 2]


Problem 11
Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
Sample output:
Original array:
[ 70 50 20 30 -11 60 50 40]
After partitioning on 4 the position:
[-11 30 20 40 50 50 60 70]

In [37]:
x = np.array([70,50,20,30,-11,60,50,40])
print(np.partition(x,4))

[-11  30  20  40  50  50  60  70]


Problem 12
Compute the euclidean distance between two arrays a and b.
Input:
[1,2,3,4,5]
[4,5,6,7,8]
Euclidean distance is: 6.7082


In [42]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(b-a)
print(np.sqrt(np.sum(np.square(b-a))))

[3 3 3 3 3]
6.708203932499369


Problem 13
Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
Input:
array([1, 3, 7, 1, 2, 6, 0, 1])
Desired Output:
array( [2, 5])
where, 2 and 5 are the positions of peak values 7 and 6.

In [50]:
arr=np.array([1, 3, 7, 1, 2, 6, 0, 1])
li=[]
for i in range(len(arr)-1):
    if(arr[i]>arr[i-1] and arr[i]>arr[i+1]):
        li.append(i)

print(li)

[2, 5]


Problem 14
Find the index of nth repetition of number i .
Inputs
array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5 (from user)
i = 1 (from user)
Output
8

In [52]:
a = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = int(input("enter value of n"))
i = int(input("enter value of i"))

print(np.where(a==i)[0][n-1])

8
