In [3]:
import numpy as np

print(np.__version__)
print(np.__package__)


1.26.2
numpy


In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [22]:
a = np.array([0,0,0,0,0])
print(np.all(a))


False


In [23]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

print(np.add(a,b,dtype=int))

[6 6 6 6 6]


In [32]:
print(np.linspace(0,15,14,dtype=int))

[ 0  1  2  3  4  5  6  8  9 10 11 12 13 15]


In [48]:
a = np.array([10,20,np.nan,np.inf])
print(np.isfinite(a))
print(np.isinf(a))
print(np.isnan(a))
print(a[np.logical_not(np.isnan(a))])

[ True  True False False]
[False False False  True]
[False False  True False]
[10. 20. inf]


In [49]:
print(np.info(np.isscalar))

 isscalar(element)

Returns True if the type of `element` is a scalar type.

Parameters
----------
element : any
    Input argument, can be of any type and shape.

Returns
-------
val : bool
    True if `element` is a scalar type, False if it is not.

See Also
--------
ndim : Get the number of dimensions of an array

Notes
-----
If you need a stricter way to identify a *numerical* scalar, use
``isinstance(x, numbers.Number)``, as that returns ``False`` for most
non-numerical elements such as strings.

In most cases ``np.ndim(x) == 0`` should be used instead of this function,
as that will also return true for 0d arrays. This is how numpy overloads
functions in the style of the ``dx`` arguments to `gradient` and the ``bins``
argument to `histogram`. Some key differences:

+--------------------------------------+---------------+-------------------+
| x                                    |``isscalar(x)``|``np.ndim(x) == 0``|
+======================================+===============+=========

In [63]:
print(np.allclose([1,2.21111],[1,2.211101]))

True


In [70]:
x = np.array([3,5])
y = np.array([2,5])

print(np.greater(x,y))
print(np.equal(x,y))
print(np.less_equal(x,y))

[ True False]
[False  True]
[False  True]


In [74]:
x = np.array([1,7,13,105])
print(x.size*x.itemsize)

16


In [78]:
array = np.zeros(10,dtype=int)
print(array)
array = np.ones(10,dtype=int)
print(array)


[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


In [80]:
print(np.info(np.matrix))

 matrix(data, dtype=None, copy=True)

matrix(data, dtype=None, copy=True)

.. note:: It is no longer recommended to use this class, even for linear
          algebra. Instead use regular arrays. The class may be removed
          in the future.

Returns a matrix from an array-like object, or from a string of data.
A matrix is a specialized 2-D array that retains its 2-D nature
through operations.  It has certain special operators, such as ``*``
(matrix multiplication) and ``**`` (matrix power).

Parameters
----------
data : array_like or string
   If `data` is a string, it is interpreted as a matrix with commas
   or spaces separating columns, and semicolons separating rows.
dtype : data-type
   Data-type of the output matrix.
copy : bool
   If `data` is already an `ndarray`, then this flag determines
   whether the data is copied (the default), or whether a view is
   constructed.

See Also
--------
array

Examples
--------
>>> a = np.matrix('1 2; 3 4')
>>> a
matrix([[1, 2],
        [

In [162]:
n = int(input("Enter the size of matrix"))
a = np.zeros((n,n),dtype=int)
a[1][0] = 1
a[1][1] = 1
a[1][2] = 1
# print(a)
for i in a:
    print(i) 

[0 0 0]
[1 1 1]
[0 0 0]


In [177]:
a = np.zeros(shape=(3,4),dtype='int')

a[1:2:1  ,  1:3:1] = 3
print(a)


[[0 0 0 0]
 [0 3 3 0]
 [0 0 0 0]]


In [179]:
a = np.arange(2,12)
a = a[::-1]
print(a)

[11 10  9  8  7  6  5  4  3  2]


In [181]:
a = [1,2,3,4,5,6,7,8]
a = np.asfarray(a)
print(a)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [190]:
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

print(a[::1,::1])
print("------------------------")
print(a[::-1,::1])
print("------------------------")
print(a[::1,::-1])
print("------------------------")
print(a[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------
[[7 8 9]
 [4 5 6]
 [1 2 3]]
------------------------
[[3 2 1]
 [6 5 4]
 [9 8 7]]
------------------------
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [214]:
a = np.ones(shape=(4,4),dtype="int")
a[1:-1:1 , 1:-1:1 ]=0
print(a)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [218]:
a = np.ones(shape=(8,8),dtype="int")
a[::2 , ::2 ]=0
a[1::2 , 1::2 ]=0
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [220]:
arr = [1,2,3,4,5,6,7,8,9]
a = np.asarray(arr)
print(a)

my_tuple = ([8,4,6],[1,2,3])
print(np.asarray(my_tuple))

[1 2 3 4 5 6 7 8 9]
[[8 4 6]
 [1 2 3]]


In [228]:
a = np.empty((3,4))
print(a)
a = np.full((3,3),6)
print(a)

[[1.01855798e-312 1.10343781e-312 1.01855798e-312 9.54898106e-313]
 [1.12465777e-312 1.03977794e-312 1.23075756e-312 1.01855798e-312]
 [1.12465777e-312 9.76118064e-313 1.20953760e-312 1.90979621e-312]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [236]:
a = [0, 12, 45.21, 34, 99.91, 32]
a = np.asfarray(a)
print(np.round((5*(a-32)/9),2))

[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [242]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0,40])
print(np.in1d(array1,array2))

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10,30,40])
print(array1[np.in1d(array1,array2)])

[ True False False  True False]
[10 40]


In [244]:
array1 = np.array([10, 10,10,20,20, 20, 40, 40,40])

print(np.unique(array1))

[10 20 40]


In [248]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10,30])
print(np.setdiff1d(array1,array2))

[ 0 20 40 60]


In [250]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10,20])
print(np.setxor1d(array1,array2))

[ 0 40 60]


In [253]:
array1 = np.array([12, 10, 20, 40, 60])
print(np.all(array1))

True


In [256]:
arr = [1,2,3,4]
print(np.tile(arr,3))

[1 2 3 4 1 2 3 4 1 2 3 4]


In [267]:
x = np.diagflat([1,2,3,4,5,6,7,8,9])
print(x)

# x  = np.eye(10,dtype="int")
# print(x)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [274]:
x = np.array([[0,10,20],[20,30,40]])

print(x[np.where(x>10)])


[20 20 30 40]


In [280]:
x = np.array([[10, 20, 30], [20, 40, 50],[20,21,32]])
print(np.ravel(x))
print(x.reshape(3,3))

[10 20 30 20 40 50 20 21 32]
[[10 20 30]
 [20 40 50]
 [20 21 32]]
